name: ARkea
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  animate_do: any
  cloudinary: ^1.1.0
  cupertino_icons: ^1.0.2
  dart_ipify: ^1.1.1
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  flutter_svg: ^2.0.2
  uni_links: ^0.5.1
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.0.2
  http: ^0.13.5
  image_picker: ^0.8.7
  intl_phone_field: ^3.1.0
  line_awesome_flutter: ^2.0.0
  line_icons: ^2.0.1
  network_info_plus: ^3.0.2
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.17
  smooth_page_indicator: ^1.0.1
  quickalert: ^1.0.1
  model_viewer_plus: ^1.4.0
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  string_to_color: ^2.0.0
  flutter_stripe: ^9.1.1
  badges: ^3.1.1
  convert: ^3.1.1
  timeago: ^3.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-Regular.ttf
          # weight: 500
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish-Italic.ttf
        - asset: assets/fonts/Klasik Regular.otf
          style: italic
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita_Regular.otf
        - asset: assets/fonts/Gordita_Medium.otf
          weight: 500
        - asset: assets/fonts/Gordita_Bold.otf
          weight: 700
        - asset: assets/fonts/Gordita_Light.otf
          weight: 300
